apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-prod
  namespace: anand-manifest
  labels:
    app: hello-prod
spec:
  selector:
    matchLabels:
      app: hello-prod
  template:
    metadata:
      labels:
        app: hello-prod
    spec:
      containers:
      - name: hello
        image: linuxacademycontent/gitops:hellov1.2
